### ISSUE TITLE
Hi,thanks for you best work!I want to know how to test,and where is testvideo()' or 'testvideos()' functions?

### ISSUE THREAD

**Issue by houqian2180320171** [psychopa4/PFNL#1]

**Comment by psychopa4** [comment]
Different video SR models process video frames in a specific way, thus, the 'testvideo()' function needs to be customized. The 'testvideo()' function can be found in each model file, e.g. ./model/pfnl.py .

**Comment by houqian2180320171** [comment]
OK,Thank you very much!




------------------ 原始邮件 ------------------
发件人: "psychopa4"<notifications@github.com>;
发送时间: 2019年10月28日(星期一) 上午7:48
收件人: "psychopa4/PFNL"<PFNL@noreply.github.com>;
抄送: "上善若水"<2570725376@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [psychopa4/PFNL] Hi,thanks for you best work!I want to know howto test,and where is testvideo()' or 'testvideos()' functions? (#1)




Different video SR models process video frames in a specific way, thus, the 'testvideo()' function needs to be customized. The 'testvideo()' function can be found in each model file, e.g. ./model/pfnl.py .

**Comment by houqian2180320171** [comment]
你好，我是西安一所学校的研究生，我参考了您发表的论文，请问可以留一个联系方式，比如QQ或者微信，方便向您请教问题吗？




------------------ 原始邮件 ------------------
发件人: "psychopa4"<notifications@github.com>;
发送时间: 2019年10月28日(星期一) 上午7:48
收件人: "psychopa4/PFNL"<PFNL@noreply.github.com>;
抄送: "上善若水"<2570725376@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [psychopa4/PFNL] Hi,thanks for you best work!I want to know howto test,and where is testvideo()' or 'testvideos()' functions? (#1)




Different video SR models process video frames in a specific way, thus, the 'testvideo()' function needs to be customized. The 'testvideo()' function can be found in each model file, e.g. ./model/pfnl.py .

**Comment by psychopa4** [comment]
我的微信: yao13052781082




------------------ 原始邮件 ------------------
发件人: "houqian2180320171"<notifications@github.com>;
发送时间: 2019年10月28日(星期一) 晚上9:22
收件人: "psychopa4/PFNL"<PFNL@noreply.github.com>;
抄送: "洗痕"<494459956@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [psychopa4/PFNL] Hi,thanks for you best work!I want to know howto test,and where is testvideo()' or 'testvideos()' functions? (#1)



你好，我是西安一所学校的研究生，我参考了您发表的论文，请问可以留一个联系方式，比如QQ或者微信，方便向您请教问题吗？ 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "psychopa4"<notifications@github.com>; 
 发送时间: 2019年10月28日(星期一) 上午7:48 
 收件人: "psychopa4/PFNL"<PFNL@noreply.github.com>; 
 抄送: "上善若水"<2570725376@qq.com>;"Author"<author@noreply.github.com>; 
 主题: Re: [psychopa4/PFNL] Hi,thanks for you best work!I want to know howto test,and where is testvideo()' or 'testvideos()' functions? (#1) 
 
 
 
 
 Different video SR models process video frames in a specific way, thus, the 'testvideo()' function needs to be customized. The 'testvideo()' function can be found in each model file, e.g. ./model/pfnl.py .

**Comment by houqian2180320171** [comment]
您好，你的微信号我加不上，显示用户不存在


------------------ 原始邮件 ------------------
发件人: "psychopa4"<notifications@github.com>;
发送时间: 2019年10月28日(星期一) 晚上10:00
收件人: "psychopa4/PFNL"<PFNL@noreply.github.com>;
抄送: "上善若水"<2570725376@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [psychopa4/PFNL] Hi,thanks for you best work!I want to know howto test,and where is testvideo()' or 'testvideos()' functions? (#1)



我的微信: yao13052781082 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "houqian2180320171"<notifications@github.com>; 
 发送时间: 2019年10月28日(星期一) 晚上9:22 
 收件人: "psychopa4/PFNL"<PFNL@noreply.github.com>; 
 抄送: "洗痕"<494459956@qq.com>;"State change"<state_change@noreply.github.com>; 
 主题: Re: [psychopa4/PFNL] Hi,thanks for you best work!I want to know howto test,and where is testvideo()' or 'testvideos()' functions? (#1) 
 
 
 
 你好，我是西安一所学校的研究生，我参考了您发表的论文，请问可以留一个联系方式，比如QQ或者微信，方便向您请教问题吗？  
   
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: "psychopa4"<notifications@github.com>;  
  发送时间: 2019年10月28日(星期一) 上午7:48  
  收件人: "psychopa4/PFNL"<PFNL@noreply.github.com>;  
  抄送: "上善若水"<2570725376@qq.com>;"Author"<author@noreply.github.com>;  
  主题: Re: [psychopa4/PFNL] Hi,thanks for you best work!I want to know howto test,and where is testvideo()' or 'testvideos()' functions? (#1)  
   
   
   
   
  Different video SR models process video frames in a specific way, thus, the 'testvideo()' function needs to be customized. The 'testvideo()' function can be found in each model file, e.g. ./model/pfnl.py .

**Comment by houqian2180320171** [comment]
您好，您的微信号我加不上，请问你可以加一下我吗？我的微信号h2570725376




------------------ 原始邮件 ------------------
发件人: "psychopa4"<notifications@github.com>;
发送时间: 2019年10月28日(星期一) 晚上10:00
收件人: "psychopa4/PFNL"<PFNL@noreply.github.com>;
抄送: "上善若水"<2570725376@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [psychopa4/PFNL] Hi,thanks for you best work!I want to know howto test,and where is testvideo()' or 'testvideos()' functions? (#1)



我的微信: yao13052781082 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "houqian2180320171"<notifications@github.com>; 
 发送时间: 2019年10月28日(星期一) 晚上9:22 
 收件人: "psychopa4/PFNL"<PFNL@noreply.github.com>; 
 抄送: "洗痕"<494459956@qq.com>;"State change"<state_change@noreply.github.com>; 
 主题: Re: [psychopa4/PFNL] Hi,thanks for you best work!I want to know howto test,and where is testvideo()' or 'testvideos()' functions? (#1) 
 
 
 
 你好，我是西安一所学校的研究生，我参考了您发表的论文，请问可以留一个联系方式，比如QQ或者微信，方便向您请教问题吗？  
   
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: "psychopa4"<notifications@github.com>;  
  发送时间: 2019年10月28日(星期一) 上午7:48  
  收件人: "psychopa4/PFNL"<PFNL@noreply.github.com>;  
  抄送: "上善若水"<2570725376@qq.com>;"Author"<author@noreply.github.com>;  
  主题: Re: [psychopa4/PFNL] Hi,thanks for you best work!I want to know howto test,and where is testvideo()' or 'testvideos()' functions? (#1)  
   
   
   
   
  Different video SR models process video frames in a specific way, thus, the 'testvideo()' function needs to be customized. The 'testvideo()' function can be found in each model file, e.g. ./model/pfnl.py .

**Comment by psychopa4** [comment]
二维码已添加至附件




------------------ 原始邮件 ------------------
发件人: "houqian2180320171"<notifications@github.com>;
发送时间: 2019年10月28日(星期一) 晚上10:03
收件人: "psychopa4/PFNL"<PFNL@noreply.github.com>;
抄送: "洗痕"<494459956@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [psychopa4/PFNL] Hi,thanks for you best work!I want to know howto test,and where is testvideo()' or 'testvideos()' functions? (#1)



您好，你的微信号我加不上，显示用户不存在 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "psychopa4"<notifications@github.com>; 
 发送时间: 2019年10月28日(星期一) 晚上10:00 
 收件人: "psychopa4/PFNL"<PFNL@noreply.github.com>; 
 抄送: "上善若水"<2570725376@qq.com>;"Author"<author@noreply.github.com>; 
 主题: Re: [psychopa4/PFNL] Hi,thanks for you best work!I want to know howto test,and where is testvideo()' or 'testvideos()' functions? (#1) 
 
 
 
 我的微信: yao13052781082  
   
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: "houqian2180320171"<notifications@github.com>;  
  发送时间: 2019年10月28日(星期一) 晚上9:22  
  收件人: "psychopa4/PFNL"<PFNL@noreply.github.com>;  
  抄送: "洗痕"<494459956@qq.com>;"State change"<state_change@noreply.github.com>;  
  主题: Re: [psychopa4/PFNL] Hi,thanks for you best work!I want to know howto test,and where is testvideo()' or 'testvideos()' functions? (#1)  
   
   
   
  你好，我是西安一所学校的研究生，我参考了您发表的论文，请问可以留一个联系方式，比如QQ或者微信，方便向您请教问题吗？   
     
     
     
     
   ------------------ 原始邮件 ------------------   
   发件人: "psychopa4"<notifications@github.com>;   
   发送时间: 2019年10月28日(星期一) 上午7:48   
   收件人: "psychopa4/PFNL"<PFNL@noreply.github.com>;   
   抄送: "上善若水"<2570725376@qq.com>;"Author"<author@noreply.github.com>;   
   主题: Re: [psychopa4/PFNL] Hi,thanks for you best work!I want to know howto test,and where is testvideo()' or 'testvideos()' functions? (#1)   
     
     
     
     
   Different video SR models process video frames in a specific way, thus, the 'testvideo()' function needs to be customized. The 'testvideo()' function can be found in each model file, e.g. ./model/pfnl.py .

**Comment by houqian2180320171** [comment]
您好，我这边附件没有显示二维码，可以麻烦您加一下我吗？我的已添加至附件




------------------ 原始邮件 ------------------
发件人: "psychopa4"<notifications@github.com>;
发送时间: 2019年10月28日(星期一) 晚上10:08
收件人: "psychopa4/PFNL"<PFNL@noreply.github.com>;
抄送: "上善若水"<2570725376@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [psychopa4/PFNL] Hi,thanks for you best work!I want to know howto test,and where is testvideo()' or 'testvideos()' functions? (#1)



二维码已添加至附件 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "houqian2180320171"<notifications@github.com>; 
 发送时间: 2019年10月28日(星期一) 晚上10:03 
 收件人: "psychopa4/PFNL"<PFNL@noreply.github.com>; 
 抄送: "洗痕"<494459956@qq.com>;"State change"<state_change@noreply.github.com>; 
 主题: Re: [psychopa4/PFNL] Hi,thanks for you best work!I want to know howto test,and where is testvideo()' or 'testvideos()' functions? (#1) 
 
 
 
 您好，你的微信号我加不上，显示用户不存在  
   
   
  ------------------ 原始邮件 ------------------  
  发件人: "psychopa4"<notifications@github.com>;  
  发送时间: 2019年10月28日(星期一) 晚上10:00  
  收件人: "psychopa4/PFNL"<PFNL@noreply.github.com>;  
  抄送: "上善若水"<2570725376@qq.com>;"Author"<author@noreply.github.com>;  
  主题: Re: [psychopa4/PFNL] Hi,thanks for you best work!I want to know howto test,and where is testvideo()' or 'testvideos()' functions? (#1)  
   
   
   
  我的微信: yao13052781082   
     
     
     
     
   ------------------ 原始邮件 ------------------   
   发件人: "houqian2180320171"<notifications@github.com>;   
   发送时间: 2019年10月28日(星期一) 晚上9:22   
   收件人: "psychopa4/PFNL"<PFNL@noreply.github.com>;   
   抄送: "洗痕"<494459956@qq.com>;"State change"<state_change@noreply.github.com>;   
   主题: Re: [psychopa4/PFNL] Hi,thanks for you best work!I want to know howto test,and where is testvideo()' or 'testvideos()' functions? (#1)   
     
     
     
   你好，我是西安一所学校的研究生，我参考了您发表的论文，请问可以留一个联系方式，比如QQ或者微信，方便向您请教问题吗？    
       
       
       
       
    ------------------ 原始邮件 ------------------    
    发件人: "psychopa4"<notifications@github.com>;    
    发送时间: 2019年10月28日(星期一) 上午7:48    
    收件人: "psychopa4/PFNL"<PFNL@noreply.github.com>;    
    抄送: "上善若水"<2570725376@qq.com>;"Author"<author@noreply.github.com>;    
    主题: Re: [psychopa4/PFNL] Hi,thanks for you best work!I want to know howto test,and where is testvideo()' or 'testvideos()' functions? (#1)    
       
       
       
       
    Different video SR models process video frames in a specific way, thus, the 'testvideo()' function needs to be customized. The 'testvideo()' function can be found in each model file, e.g. ./model/pfnl.py .
