### ISSUE TITLE
error：   got shape [522], but wanted [522, 32].

### ISSUE THREAD

**Issue by hiredd** [psychopa4/PFNL#11]
when run：  inList_all = tf.convert_to_tensor(inList_all, dtype=tf.string)   get error as follows：
got shape [522], but wanted [522, 32].

can anyone help me

my tensorflow is 1.12

**Comment by billhhh** [comment]
May I know how did you solve this problem?

**Comment by billhhh** [comment]
Got it, caused by path of LCF. The next time once you tried to close a problem. plz post your solution thx
