### ISSUE TITLE
non-local module contains no information about temporal frames

### ISSUE THREAD

**Issue by oliverxudd** [psychopa4/PFNL#16]
Hi, pyschopa4, thanks for your good work!
I have a question about your nonlocal module from fig4 in the paper.
![图1](https://user-images.githubusercontent.com/55381843/93038002-69cf7980-f676-11ea-830c-211710d38d7e.PNG)
**F** in the figure is HW/(r^2) x HW/(r^2), which after softmax will multiply Y, so **F** contains spatial correlation only, because temporal channel is used as feature channel. 
So, How does this module model motion between temporal frames? It seems to me temporal weights remain same for all temporal frames because **F** contains no temporal info.

**Comment by psychopa4** [comment]
A pixel in _F_ could be computed from different spatial positions from X, which is why F contains temporal correlations.
Please see the Figure below.
![nlc](https://user-images.githubusercontent.com/22425078/93408485-44857a00-f8c7-11ea-95fb-8335e04a18fb.jpg)

**Comment by oliverxudd** [comment]
thanks for the clarification!
