### ISSUE TITLE
Alternative test dataset source

### ISSUE THREAD

**Issue by marwansalem** [psychopa4/PFNL#22]
is it possible to provide another source for the test datasets ; UDM10  as it is nearly impossible to download outside China, Thank you

**Comment by psychopa4** [comment]
> is it possible to provide another source for the test datasets ; UDM10 as it is nearly impossible to download outside China, Thank you

My Google drive runs out, and my VPN is down now. 
I will upload UDM10 to the international dubox once my VPN works.

**Comment by marwansalem** [comment]
Thank you

**Comment by vb000** [comment]
Hi @psychopa4, I'm having similar issues to download as well... any update on hosting it in alternative locations?

**Comment by vb000** [comment]
Hi @marwansalem, have you managed to get hold of UDM10 dataset?

**Comment by marwansalem** [comment]
Unfortunately I have not. @vb000
